application: portal-in-gae
version: 1-1
runtime: python
api_version: 1

handlers:
- url: /media
  static_dir: static
  
- url: /appengine_admin_media
  static_dir: appengine_admin/media
  secure: never  
  
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  mime_type: image/vnd.microsoft.icon

- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots.txt
    
- url: .*
  script: main.py
