application: portal-in-gae
version: 2
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /media
  static_dir: static
  
- url: /appengine_admin_media
  static_dir: appengine_admin/media
  secure: never  
  
# Your custom handler goes here (see next step)
- url: /admin/models.*
  script: handlers.admin.app
  secure: always  
  
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  mime_type: image/vnd.microsoft.icon

- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots.txt
    
- url: .*
  script: main.py

libraries:
- name: django
  version: "1.3"
  
env_variables:
  DJANGO_SETTINGS_MODULE: 'settings'